// <auto-generated />
using System;
using KiTrackerApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiTrackerApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905003812_ActualizacionMayoriaDeServicios1")]
    partial class ActualizacionMayoriaDeServicios1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("KiTrackerApi.Core.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaUltimoUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloHardware")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplicador")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Lectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaLectura")
                        .HasColumnType("TEXT");

                    b.Property<int>("LuchadorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NivelKi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaFotografia")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("LuchadorId");

                    b.ToTable("Lecturas");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Luchador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.ToTable("Luchadores");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Dispositivo", b =>
                {
                    b.HasOne("KiTrackerApi.Core.Models.Color", "Color")
                        .WithMany("Dispositivos")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Lectura", b =>
                {
                    b.HasOne("KiTrackerApi.Core.Models.Dispositivo", "Dispositivo")
                        .WithMany("Lecturas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiTrackerApi.Core.Models.Luchador", "Luchador")
                        .WithMany("Lecturas")
                        .HasForeignKey("LuchadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Luchador");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Luchador", b =>
                {
                    b.HasOne("KiTrackerApi.Core.Models.Especie", "Especie")
                        .WithMany("Luchadores")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Color", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Dispositivo", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Especie", b =>
                {
                    b.Navigation("Luchadores");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Luchador", b =>
                {
                    b.Navigation("Lecturas");
                });
#pragma warning restore 612, 618
        }
    }
}
