// <auto-generated />
using System;
using KiTrackerApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiTrackerApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919035956_AgregarTablasDeIdentity")]
    partial class AgregarTablasDeIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("KiTrackerApi.Core.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoHex = "#FF0000",
                            Descripcion = "Rojo Pasión"
                        },
                        new
                        {
                            Id = 2,
                            CodigoHex = "#00FF00",
                            Descripcion = "Verde Namek"
                        },
                        new
                        {
                            Id = 3,
                            CodigoHex = "#0000FF",
                            Descripcion = "Azul Ki"
                        },
                        new
                        {
                            Id = 4,
                            CodigoHex = "#FFFF00",
                            Descripcion = "Amarillo Super Saiyajin"
                        },
                        new
                        {
                            Id = 5,
                            CodigoHex = "#800080",
                            Descripcion = "Púrpura Real"
                        },
                        new
                        {
                            Id = 6,
                            CodigoHex = "#000000",
                            Descripcion = "Negro Azabache"
                        },
                        new
                        {
                            Id = 7,
                            CodigoHex = "#FFFFFF",
                            Descripcion = "Blanco Puro"
                        },
                        new
                        {
                            Id = 8,
                            CodigoHex = "#FFA500",
                            Descripcion = "Naranja Kame"
                        },
                        new
                        {
                            Id = 9,
                            CodigoHex = "#FFD700",
                            Descripcion = "Dorado Aura"
                        },
                        new
                        {
                            Id = 10,
                            CodigoHex = "#C0C0C0",
                            Descripcion = "Plateado Metálico"
                        });
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaUltimoUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloHardware")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Dispositivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 1,
                            FechaUltimoUso = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-SCOUTER-RED-01",
                            ModeloHardware = "iPhone 15 Pro Max",
                            Tipo = "mobile"
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 2,
                            FechaUltimoUso = new DateTime(2026, 8, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-SCOUTER-GRN-02",
                            ModeloHardware = "Samsung Galaxy S24 Ultra",
                            Tipo = "mobile"
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 3,
                            FechaUltimoUso = new DateTime(2026, 8, 15, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-SCOUTER-BLU-03",
                            ModeloHardware = "MacBook Pro 16 M3",
                            Tipo = "web"
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 4,
                            FechaUltimoUso = new DateTime(2026, 8, 20, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-CAPSULE-001",
                            ModeloHardware = "Google Pixel 8 Pro",
                            Tipo = "mobile"
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 9,
                            FechaUltimoUso = new DateTime(2026, 8, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-CAPSULE-002",
                            ModeloHardware = "Dell XPS 15 9530",
                            Tipo = "web"
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 6,
                            FechaUltimoUso = new DateTime(2026, 8, 28, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-REDRIBBON-01",
                            ModeloHardware = "Xiaomi 14 Pro",
                            Tipo = "mobile"
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 5,
                            FechaUltimoUso = new DateTime(2026, 8, 30, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-BABIDI-MAG-01",
                            ModeloHardware = "Lenovo ThinkPad X1 Carbon",
                            Tipo = "web"
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 5,
                            FechaUltimoUso = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-SCOUTER-PUR-04",
                            ModeloHardware = "OnePlus 12",
                            Tipo = "mobile"
                        },
                        new
                        {
                            Id = 9,
                            ColorId = 7,
                            FechaUltimoUso = new DateTime(2026, 9, 5, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-CAPSULE-003",
                            ModeloHardware = "ASUS ROG Zephyrus G16",
                            Tipo = "web"
                        },
                        new
                        {
                            Id = 10,
                            ColorId = 9,
                            FechaUltimoUso = new DateTime(2026, 9, 10, 8, 22, 0, 0, DateTimeKind.Unspecified),
                            Fingerprint = "FP-SCOUTER-GLD-05",
                            ModeloHardware = "HP Spectre x360",
                            Tipo = "web"
                        });
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplicador")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Especies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Saiyajin",
                            Multiplicador = 1.5
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Humano",
                            Multiplicador = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Namekuseijin",
                            Multiplicador = 1.2
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Raza de Freezer",
                            Multiplicador = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Androide / Bio-Androide",
                            Multiplicador = 1.8
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Majin",
                            Multiplicador = 2.5
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Shin-jin (Dios)",
                            Multiplicador = 5.0
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Habitante del Más Allá",
                            Multiplicador = 1.1000000000000001
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Tritón Alienígena",
                            Multiplicador = 1.3
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Alienígena Desconocido",
                            Multiplicador = 1.3999999999999999
                        });
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Lectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaLectura")
                        .HasColumnType("TEXT");

                    b.Property<int>("LuchadorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NivelKi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaFotografia")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("LuchadorId");

                    b.ToTable("Lecturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 3, 24, 5, 57, 33, 0, DateTimeKind.Unspecified),
                            LuchadorId = 32,
                            NivelKi = 21715456L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_nino_lectura_1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DispositivoId = 3,
                            FechaLectura = new DateTime(2026, 8, 5, 7, 29, 43, 0, DateTimeKind.Unspecified),
                            LuchadorId = 8,
                            NivelKi = 11776L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/tenshinhan_lectura_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DispositivoId = 10,
                            FechaLectura = new DateTime(2026, 3, 1, 20, 30, 19, 0, DateTimeKind.Unspecified),
                            LuchadorId = 21,
                            NivelKi = 22000L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/dodoria_lectura_3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 5, 12, 3, 52, 13, 0, DateTimeKind.Unspecified),
                            LuchadorId = 10,
                            NivelKi = 610L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/chaoz_lectura_4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 4, 20, 8, 44, 3, 0, DateTimeKind.Unspecified),
                            LuchadorId = 27,
                            NivelKi = 10079L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/guldo_lectura_5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 4, 6, 19, 54, 12, 0, DateTimeKind.Unspecified),
                            LuchadorId = 16,
                            NivelKi = 320000000L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/androide_16_lectura_6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            DispositivoId = 10,
                            FechaLectura = new DateTime(2026, 7, 28, 2, 0, 3, 0, DateTimeKind.Unspecified),
                            LuchadorId = 12,
                            NivelKi = 312781498L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/cell_lectura_7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            DispositivoId = 5,
                            FechaLectura = new DateTime(2026, 2, 17, 20, 58, 36, 0, DateTimeKind.Unspecified),
                            LuchadorId = 3,
                            NivelKi = 926066226L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/gohan_lectura_8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 6, 12, 16, 5, 44, 0, DateTimeKind.Unspecified),
                            LuchadorId = 8,
                            NivelKi = 3804L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/tenshinhan_lectura_9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 5, 13, 9, 41, 27, 0, DateTimeKind.Unspecified),
                            LuchadorId = 22,
                            NivelKi = 28169L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/zarbon_lectura_10.jpg"
                        },
                        new
                        {
                            Id = 11,
                            DispositivoId = 2,
                            FechaLectura = new DateTime(2026, 2, 18, 20, 0, 54, 0, DateTimeKind.Unspecified),
                            LuchadorId = 36,
                            NivelKi = 952329L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/anciano_kaioshin_lectura_11.jpg"
                        },
                        new
                        {
                            Id = 12,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 2, 22, 5, 39, 46, 0, DateTimeKind.Unspecified),
                            LuchadorId = 37,
                            NivelKi = 4136L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/kaio_del_norte_lectura_12.jpg"
                        },
                        new
                        {
                            Id = 13,
                            DispositivoId = 3,
                            FechaLectura = new DateTime(2026, 2, 16, 15, 26, 7, 0, DateTimeKind.Unspecified),
                            LuchadorId = 32,
                            NivelKi = 43236081L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_nino_lectura_13.jpg"
                        },
                        new
                        {
                            Id = 14,
                            DispositivoId = 6,
                            FechaLectura = new DateTime(2026, 5, 19, 6, 50, 47, 0, DateTimeKind.Unspecified),
                            LuchadorId = 37,
                            NivelKi = 4106L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/kaio_del_norte_lectura_14.jpg"
                        },
                        new
                        {
                            Id = 15,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 4, 18, 10, 19, 42, 0, DateTimeKind.Unspecified),
                            LuchadorId = 37,
                            NivelKi = 4825L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/kaio_del_norte_lectura_15.jpg"
                        },
                        new
                        {
                            Id = 16,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 1, 8, 7, 11, 39, 0, DateTimeKind.Unspecified),
                            LuchadorId = 8,
                            NivelKi = 11956L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/tenshinhan_lectura_16.jpg"
                        },
                        new
                        {
                            Id = 17,
                            DispositivoId = 2,
                            FechaLectura = new DateTime(2026, 1, 20, 21, 18, 24, 0, DateTimeKind.Unspecified),
                            LuchadorId = 30,
                            NivelKi = 14L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/videl_lectura_17.jpg"
                        },
                        new
                        {
                            Id = 18,
                            DispositivoId = 3,
                            FechaLectura = new DateTime(2026, 7, 26, 21, 35, 10, 0, DateTimeKind.Unspecified),
                            LuchadorId = 8,
                            NivelKi = 10178L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/tenshinhan_lectura_18.jpg"
                        },
                        new
                        {
                            Id = 19,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 4, 3, 16, 21, 40, 0, DateTimeKind.Unspecified),
                            LuchadorId = 3,
                            NivelKi = 81373511L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/gohan_lectura_19.jpg"
                        },
                        new
                        {
                            Id = 20,
                            DispositivoId = 2,
                            FechaLectura = new DateTime(2026, 6, 3, 15, 2, 18, 0, DateTimeKind.Unspecified),
                            LuchadorId = 20,
                            NivelKi = 4000L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/nappa_lectura_20.jpg"
                        },
                        new
                        {
                            Id = 21,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 7, 28, 9, 44, 3, 0, DateTimeKind.Unspecified),
                            LuchadorId = 12,
                            NivelKi = 378809462L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/cell_lectura_21.jpg"
                        },
                        new
                        {
                            Id = 22,
                            DispositivoId = 7,
                            FechaLectura = new DateTime(2026, 1, 20, 21, 55, 25, 0, DateTimeKind.Unspecified),
                            LuchadorId = 10,
                            NivelKi = 610L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/chaoz_lectura_22.jpg"
                        },
                        new
                        {
                            Id = 23,
                            DispositivoId = 7,
                            FechaLectura = new DateTime(2026, 7, 16, 21, 37, 37, 0, DateTimeKind.Unspecified),
                            LuchadorId = 8,
                            NivelKi = 15302L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/tenshinhan_lectura_23.jpg"
                        },
                        new
                        {
                            Id = 24,
                            DispositivoId = 10,
                            FechaLectura = new DateTime(2026, 7, 16, 12, 0, 30, 0, DateTimeKind.Unspecified),
                            LuchadorId = 24,
                            NivelKi = 56213L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/recoome_lectura_24.jpg"
                        },
                        new
                        {
                            Id = 25,
                            DispositivoId = 2,
                            FechaLectura = new DateTime(2026, 5, 2, 13, 30, 17, 0, DateTimeKind.Unspecified),
                            LuchadorId = 16,
                            NivelKi = 320000000L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/androide_16_lectura_25.jpg"
                        },
                        new
                        {
                            Id = 26,
                            DispositivoId = 4,
                            FechaLectura = new DateTime(2026, 6, 18, 5, 27, 14, 0, DateTimeKind.Unspecified),
                            LuchadorId = 29,
                            NivelKi = 13L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/mr_satan_lectura_26.jpg"
                        },
                        new
                        {
                            Id = 27,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 2, 9, 3, 34, 52, 0, DateTimeKind.Unspecified),
                            LuchadorId = 6,
                            NivelKi = 32742L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/krillin_lectura_27.jpg"
                        },
                        new
                        {
                            Id = 28,
                            DispositivoId = 3,
                            FechaLectura = new DateTime(2026, 2, 27, 8, 34, 3, 0, DateTimeKind.Unspecified),
                            LuchadorId = 4,
                            NivelKi = 175658608L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_futuro_lectura_28.jpg"
                        },
                        new
                        {
                            Id = 29,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 7, 28, 7, 15, 38, 0, DateTimeKind.Unspecified),
                            LuchadorId = 32,
                            NivelKi = 11186762L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_nino_lectura_29.jpg"
                        },
                        new
                        {
                            Id = 30,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 1, 22, 5, 52, 16, 0, DateTimeKind.Unspecified),
                            LuchadorId = 27,
                            NivelKi = 10398L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/guldo_lectura_30.jpg"
                        },
                        new
                        {
                            Id = 31,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 8, 28, 22, 38, 9, 0, DateTimeKind.Unspecified),
                            LuchadorId = 12,
                            NivelKi = 794354291L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/cell_lectura_31.jpg"
                        },
                        new
                        {
                            Id = 32,
                            DispositivoId = 2,
                            FechaLectura = new DateTime(2026, 6, 3, 7, 17, 49, 0, DateTimeKind.Unspecified),
                            LuchadorId = 25,
                            NivelKi = 55760L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/burter_lectura_32.jpg"
                        },
                        new
                        {
                            Id = 33,
                            DispositivoId = 4,
                            FechaLectura = new DateTime(2026, 4, 12, 16, 36, 20, 0, DateTimeKind.Unspecified),
                            LuchadorId = 17,
                            NivelKi = 11166316L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/androide_19_lectura_33.jpg"
                        },
                        new
                        {
                            Id = 34,
                            DispositivoId = 7,
                            FechaLectura = new DateTime(2026, 6, 25, 11, 42, 38, 0, DateTimeKind.Unspecified),
                            LuchadorId = 28,
                            NivelKi = 29L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/dende_lectura_34.jpg"
                        },
                        new
                        {
                            Id = 35,
                            DispositivoId = 6,
                            FechaLectura = new DateTime(2026, 8, 16, 18, 4, 47, 0, DateTimeKind.Unspecified),
                            LuchadorId = 24,
                            NivelKi = 59005L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/recoome_lectura_35.jpg"
                        },
                        new
                        {
                            Id = 36,
                            DispositivoId = 7,
                            FechaLectura = new DateTime(2026, 4, 18, 5, 7, 37, 0, DateTimeKind.Unspecified),
                            LuchadorId = 18,
                            NivelKi = 17997973L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/dr_gero_lectura_36.jpg"
                        },
                        new
                        {
                            Id = 37,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 5, 2, 19, 25, 21, 0, DateTimeKind.Unspecified),
                            LuchadorId = 32,
                            NivelKi = 100720272L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_nino_lectura_37.jpg"
                        },
                        new
                        {
                            Id = 38,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 6, 6, 0, 54, 15, 0, DateTimeKind.Unspecified),
                            LuchadorId = 35,
                            NivelKi = 217686523L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/kibito_lectura_38.jpg"
                        },
                        new
                        {
                            Id = 39,
                            DispositivoId = 7,
                            FechaLectura = new DateTime(2026, 6, 26, 21, 28, 13, 0, DateTimeKind.Unspecified),
                            LuchadorId = 32,
                            NivelKi = 103986927L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_nino_lectura_39.jpg"
                        },
                        new
                        {
                            Id = 40,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 5, 18, 10, 14, 26, 0, DateTimeKind.Unspecified),
                            LuchadorId = 39,
                            NivelKi = 10000L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/bardock_lectura_40.jpg"
                        },
                        new
                        {
                            Id = 41,
                            DispositivoId = 9,
                            FechaLectura = new DateTime(2026, 6, 4, 12, 0, 19, 0, DateTimeKind.Unspecified),
                            LuchadorId = 1,
                            NivelKi = 135706509L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/goku_lectura_41.jpg"
                        },
                        new
                        {
                            Id = 42,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 4, 26, 18, 43, 8, 0, DateTimeKind.Unspecified),
                            LuchadorId = 22,
                            NivelKi = 28691L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/zarbon_lectura_42.jpg"
                        },
                        new
                        {
                            Id = 43,
                            DispositivoId = 7,
                            FechaLectura = new DateTime(2026, 3, 22, 2, 2, 18, 0, DateTimeKind.Unspecified),
                            LuchadorId = 12,
                            NivelKi = 269784132L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/cell_lectura_43.jpg"
                        },
                        new
                        {
                            Id = 44,
                            DispositivoId = 2,
                            FechaLectura = new DateTime(2026, 2, 17, 3, 59, 36, 0, DateTimeKind.Unspecified),
                            LuchadorId = 8,
                            NivelKi = 14357L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/tenshinhan_lectura_44.jpg"
                        },
                        new
                        {
                            Id = 45,
                            DispositivoId = 3,
                            FechaLectura = new DateTime(2026, 7, 28, 9, 21, 49, 0, DateTimeKind.Unspecified),
                            LuchadorId = 27,
                            NivelKi = 10567L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/guldo_lectura_45.jpg"
                        },
                        new
                        {
                            Id = 46,
                            DispositivoId = 5,
                            FechaLectura = new DateTime(2026, 4, 6, 9, 47, 11, 0, DateTimeKind.Unspecified),
                            LuchadorId = 13,
                            NivelKi = 1530960573L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/majin_boo_lectura_46.jpg"
                        },
                        new
                        {
                            Id = 47,
                            DispositivoId = 8,
                            FechaLectura = new DateTime(2026, 3, 24, 5, 7, 37, 0, DateTimeKind.Unspecified),
                            LuchadorId = 2,
                            NivelKi = 31057418L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/vegeta_lectura_47.jpg"
                        },
                        new
                        {
                            Id = 48,
                            DispositivoId = 1,
                            FechaLectura = new DateTime(2026, 1, 20, 4, 9, 59, 0, DateTimeKind.Unspecified),
                            LuchadorId = 32,
                            NivelKi = 56934520L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/trunks_nino_lectura_48.jpg"
                        },
                        new
                        {
                            Id = 49,
                            DispositivoId = 10,
                            FechaLectura = new DateTime(2026, 1, 21, 2, 8, 42, 0, DateTimeKind.Unspecified),
                            LuchadorId = 7,
                            NivelKi = 175L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/roshi_lectura_49.jpg"
                        },
                        new
                        {
                            Id = 50,
                            DispositivoId = 10,
                            FechaLectura = new DateTime(2026, 1, 9, 3, 31, 7, 0, DateTimeKind.Unspecified),
                            LuchadorId = 40,
                            NivelKi = 2816913501L,
                            RutaFotografia = "https://kitracker.blob.core.windows.net/lecturas/broly_lectura_50.jpg"
                        });
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Luchador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.ToTable("Luchadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 2, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/goku.jpg",
                            Nombre = "Son Goku"
                        },
                        new
                        {
                            Id = 2,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/vegeta.jpg",
                            Nombre = "Vegeta"
                        },
                        new
                        {
                            Id = 3,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/gohan.jpg",
                            Nombre = "Son Gohan"
                        },
                        new
                        {
                            Id = 4,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 5, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/trunks_futuro.jpg",
                            Nombre = "Trunks del Futuro"
                        },
                        new
                        {
                            Id = 5,
                            EspecieId = 3,
                            FechaRegistro = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/piccolo.jpg",
                            Nombre = "Piccolo"
                        },
                        new
                        {
                            Id = 6,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 7, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/krillin.jpg",
                            Nombre = "Krillin"
                        },
                        new
                        {
                            Id = 7,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 8, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/roshi.jpg",
                            Nombre = "Maestro Roshi"
                        },
                        new
                        {
                            Id = 8,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 9, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/tenshinhan.jpg",
                            Nombre = "Ten Shin Han"
                        },
                        new
                        {
                            Id = 9,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 10, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/yamcha.jpg",
                            Nombre = "Yamcha"
                        },
                        new
                        {
                            Id = 10,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 11, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/chaoz.jpg",
                            Nombre = "Chaoz"
                        },
                        new
                        {
                            Id = 11,
                            EspecieId = 4,
                            FechaRegistro = new DateTime(2026, 12, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/freezer.jpg",
                            Nombre = "Freezer"
                        },
                        new
                        {
                            Id = 12,
                            EspecieId = 5,
                            FechaRegistro = new DateTime(2026, 1, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/cell.jpg",
                            Nombre = "Cell"
                        },
                        new
                        {
                            Id = 13,
                            EspecieId = 6,
                            FechaRegistro = new DateTime(2026, 2, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/majin_boo.jpg",
                            Nombre = "Majin Boo"
                        },
                        new
                        {
                            Id = 14,
                            EspecieId = 5,
                            FechaRegistro = new DateTime(2026, 3, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/androide_17.jpg",
                            Nombre = "Androide 17"
                        },
                        new
                        {
                            Id = 15,
                            EspecieId = 5,
                            FechaRegistro = new DateTime(2026, 4, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/androide_18.jpg",
                            Nombre = "Androide 18"
                        },
                        new
                        {
                            Id = 16,
                            EspecieId = 5,
                            FechaRegistro = new DateTime(2026, 5, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/androide_16.jpg",
                            Nombre = "Androide 16"
                        },
                        new
                        {
                            Id = 17,
                            EspecieId = 5,
                            FechaRegistro = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/androide_19.jpg",
                            Nombre = "Androide 19"
                        },
                        new
                        {
                            Id = 18,
                            EspecieId = 5,
                            FechaRegistro = new DateTime(2026, 7, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/dr_gero.jpg",
                            Nombre = "Dr. Gero (Androide 20)"
                        },
                        new
                        {
                            Id = 19,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 8, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/raditz.jpg",
                            Nombre = "Raditz"
                        },
                        new
                        {
                            Id = 20,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 9, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/nappa.jpg",
                            Nombre = "Nappa"
                        },
                        new
                        {
                            Id = 21,
                            EspecieId = 4,
                            FechaRegistro = new DateTime(2026, 10, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/dodoria.jpg",
                            Nombre = "Dodoria"
                        },
                        new
                        {
                            Id = 22,
                            EspecieId = 9,
                            FechaRegistro = new DateTime(2026, 11, 23, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/zarbon.jpg",
                            Nombre = "Zarbon"
                        },
                        new
                        {
                            Id = 23,
                            EspecieId = 10,
                            FechaRegistro = new DateTime(2026, 12, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/capitan_ginyu.jpg",
                            Nombre = "Capitán Ginyu"
                        },
                        new
                        {
                            Id = 24,
                            EspecieId = 10,
                            FechaRegistro = new DateTime(2026, 1, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/recoome.jpg",
                            Nombre = "Recoome"
                        },
                        new
                        {
                            Id = 25,
                            EspecieId = 10,
                            FechaRegistro = new DateTime(2026, 2, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/burter.jpg",
                            Nombre = "Burter"
                        },
                        new
                        {
                            Id = 26,
                            EspecieId = 10,
                            FechaRegistro = new DateTime(2026, 3, 27, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/jeice.jpg",
                            Nombre = "Jeice"
                        },
                        new
                        {
                            Id = 27,
                            EspecieId = 10,
                            FechaRegistro = new DateTime(2026, 4, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/guldo.jpg",
                            Nombre = "Guldo"
                        },
                        new
                        {
                            Id = 28,
                            EspecieId = 3,
                            FechaRegistro = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/dende.jpg",
                            Nombre = "Dende"
                        },
                        new
                        {
                            Id = 29,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 6, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/mr_satan.jpg",
                            Nombre = "Mr. Satán"
                        },
                        new
                        {
                            Id = 30,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 7, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/videl.jpg",
                            Nombre = "Videl"
                        },
                        new
                        {
                            Id = 31,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 8, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/goten.jpg",
                            Nombre = "Goten"
                        },
                        new
                        {
                            Id = 32,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 9, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/trunks_nino.jpg",
                            Nombre = "Trunks (Niño)"
                        },
                        new
                        {
                            Id = 33,
                            EspecieId = 6,
                            FechaRegistro = new DateTime(2026, 10, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/dabura.jpg",
                            Nombre = "Dabura"
                        },
                        new
                        {
                            Id = 34,
                            EspecieId = 7,
                            FechaRegistro = new DateTime(2026, 11, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/kaioshin_este.jpg",
                            Nombre = "Kaioshin del Este"
                        },
                        new
                        {
                            Id = 35,
                            EspecieId = 7,
                            FechaRegistro = new DateTime(2026, 12, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/kibito.jpg",
                            Nombre = "Kibito"
                        },
                        new
                        {
                            Id = 36,
                            EspecieId = 7,
                            FechaRegistro = new DateTime(2026, 1, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/anciano_kaioshin.jpg",
                            Nombre = "Anciano Kaioshin"
                        },
                        new
                        {
                            Id = 37,
                            EspecieId = 7,
                            FechaRegistro = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/kaio_del_norte.jpg",
                            Nombre = "King Kai (Kaio del Norte)"
                        },
                        new
                        {
                            Id = 38,
                            EspecieId = 2,
                            FechaRegistro = new DateTime(2026, 3, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/yajirobe.jpg",
                            Nombre = "Yajirobe"
                        },
                        new
                        {
                            Id = 39,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 4, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/bardock.jpg",
                            Nombre = "Bardock"
                        },
                        new
                        {
                            Id = 40,
                            EspecieId = 1,
                            FechaRegistro = new DateTime(2026, 5, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfilUrl = "https://kitracker.blob.core.windows.net/luchadores/broly.jpg",
                            Nombre = "Broly"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Dispositivo", b =>
                {
                    b.HasOne("KiTrackerApi.Core.Models.Color", "Color")
                        .WithMany("Dispositivos")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Lectura", b =>
                {
                    b.HasOne("KiTrackerApi.Core.Models.Dispositivo", "Dispositivo")
                        .WithMany("Lecturas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiTrackerApi.Core.Models.Luchador", "Luchador")
                        .WithMany("Lecturas")
                        .HasForeignKey("LuchadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Luchador");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Luchador", b =>
                {
                    b.HasOne("KiTrackerApi.Core.Models.Especie", "Especie")
                        .WithMany("Luchadores")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Color", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Dispositivo", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Especie", b =>
                {
                    b.Navigation("Luchadores");
                });

            modelBuilder.Entity("KiTrackerApi.Core.Models.Luchador", b =>
                {
                    b.Navigation("Lecturas");
                });
#pragma warning restore 612, 618
        }
    }
}
